In [3]:
#INSTALAR LIBRERIAS
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (2.3.2)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (3.10.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (4.59.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (2.3.2)
Requirement already satisfied: packaging>=20.0 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (2.3.2)
Requirement already satisfied: pandas>=1.2 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (2.3.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (3.10.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.59.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\laish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from openpyxl) (2.0.0)

In [4]:
#Importamos librer√≠as requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df= pd.read_csv('Datos_Facturaci√≥n.csv')
df

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,0,F29414,2465.0,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0.0
1,1,F29415,3926.0,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
2,2,F29416,3926.0,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
3,3,F29417,3926.0,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0.0
4,4,F29418,6813.0,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10890,10890,F40306,8842.0,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaN,3272.00,0.0,0.0
10891,10891,F40307,6218.0,NaN,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaN,504.15,0.0,0.0
10892,10892,NaN,5926.0,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaN,275.68,0.0,0.0
10893,10893,F40309,361.0,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaN,129.30,0.0,0.0
10894,10894,F40310,3011.0,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaN,517.20,0.0,0.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10895 entries, 0 to 10894
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     10895 non-null  int64
 1   CVE_DOC        10890 non-null  object
 2   CVE_CLPV       10895 non-null  float64
 3   STATUS         10886 non-null  object
 4   CVE_VEND       10847 non-null  float64
 5   FECHAELAB      10893 non-null  object
 6   FECHA_DOC      10894 non-null  object
 7   FECHA_ENT      10893 non-null  object
 8   FECHA_VEN      10895 non-null  object
 9   FECHA_CANCELA  358 non-null    object
 10  CAN_TOT        10889 non-null  float64
 11  DES_TOT        10894 non-null  float64
 12  DES_FIN        10892 non-null  float64
dtypes: float64(5), int64(1), object(7)
memory usage: 1.1+ MB

In [ ]:
## ejercicio 1  CVE_CLPV entre 1000 y 2000
df1 = df[(df["CVE_CLPV"] >= 1000) & (df["CVE_CLPV"] <= 2000)]
df1

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
18,18,F29432,1965.0,C,2.0,2019-09-05 11:05:04.000,2019-09-05,2019-09-05 00:00:00,2019-09-20,2019-09-06,976.50,0.00,0.0
22,22,F29436,1965.0,C,2.0,2019-09-06 12:01:36.000,2019-09-06,2019-09-06 00:00:00,2019-09-21,2019-09-12,976.50,0.00,0.0
65,65,F29479,1240.0,E,2.0,2019-09-11 18:38:45.000,2019-09-11,2019-09-11 00:00:00,2019-09-11,NaN,4135.00,0.00,0.0
71,71,F29485,1965.0,C,2.0,2019-09-12 12:14:28.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,2019-09-12,976.50,146.48,0.0
72,72,F29486,1965.0,E,2.0,2019-09-12 12:25:52.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,NaN,976.50,146.48,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10821,10821,F40237,1757.0,E,2.0,2023-02-24 15:18:17.570,2023-02-24,2023-02-13 00:00:00,2023-02-24,NaN,10088.40,0.00,0.0
10839,10839,F40255,1583.0,E,2.0,2023-02-28 09:15:45.753,2023-02-28,2023-02-28 00:00:00,2023-03-30,NaN,3467.35,0.00,0.0
10845,10845,F40261,1786.0,E,2.0,2023-02-28 11:15:32.527,2023-02-28,2023-03-03 00:00:00,2023-02-28,NaN,4663.80,0.00,0.0
10871,10871,F40287,1453.0,E,1.0,2023-03-01 12:58:23.397,2023-03-01,2023-02-27 00:00:00,2023-03-31,NaN,9000.00,0.00,0.0
10876,10876,F40292,1082.0,E,6.0,2023-03-02 11:00:54.770,2023-03-02,2023-03-01 00:00:00,2023-03-02,NaN,3262.00,0.00,0.0

In [20]:
df1.to_csv("df1.csv")

In [ ]:
## Ejercicio 2 todas las claves excepto 5 y 4
df2 = df[~(df["CVE_VEND"] == 5) & ~(df["CVE_VEND"] == 4)]
df2

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,0,F29414,2465.0,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0.0
1,1,F29415,3926.0,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
2,2,F29416,3926.0,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
3,3,F29417,3926.0,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0.0
4,4,F29418,6813.0,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10890,10890,F40306,8842.0,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaN,3272.00,0.0,0.0
10891,10891,F40307,6218.0,NaN,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaN,504.15,0.0,0.0
10892,10892,NaN,5926.0,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaN,275.68,0.0,0.0
10893,10893,F40309,361.0,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaN,129.30,0.0,0.0
10894,10894,F40310,3011.0,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaN,517.20,0.0,0.0

In [19]:
df2.to_csv("df2.csv")

In [ ]:
##ejercicio 3 solo 28/02/2022 
df3 =df[(df["FECHA_ENT"] == "2022-02-28 00:00:00")]
df3

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
8077,8077,F37493,4598.0,E,1.0,2022-02-28 10:56:02.460,2022-02-28,2022-02-28 00:00:00,2022-03-30,NaN,44259.0000,0.0,0.0
8078,8078,F37494,1943.0,C,2.0,2022-02-28 11:34:00.367,2022-02-28,2022-02-28 00:00:00,2022-02-28,2022-02-28,89.6800,0.0,0.0
8081,8081,F37497,1943.0,C,2.0,2022-02-28 12:05:42.377,2022-02-28,2022-02-28 00:00:00,2022-02-28,2022-02-28,89.6800,0.0,0.0
8083,8083,F37499,8573.0,E,2.0,2022-02-28 12:25:29.833,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,997.5400,0.0,0.0
8084,8084,F37500,8249.0,E,2.0,2022-02-28 12:32:46.687,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,2508.7000,0.0,0.0
8090,8090,F37506,1757.0,E,2.0,2022-02-28 13:23:45.440,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,2586.2100,0.0,0.0
8091,8091,F37507,3108.0,E,2.0,2022-02-28 13:52:43.383,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,675.4000,0.0,0.0
8092,8092,F37508,6232.0,E,2.0,2022-02-28 14:46:56.940,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,941.3965,0.0,0.0
8095,8095,F37511,8593.0,E,2.0,2022-02-28 15:20:58.040,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,218.9700,0.0,0.0
8096,8096,F37512,4766.0,E,2.0,2022-02-28 15:54:16.277,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,9450.0000,0.0,0.0
8100,8100,F37516,6179.0,E,3.0,2022-02-28 16:33:54.413,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,5951.7000,0.0,0.0
8103,8103,F37519,5150.0,E,3.0,2022-02-28 17:09:39.213,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,2040.0000,0.0,0.0
8104,8104,F37520,4527.0,E,2.0,2022-02-28 17:14:57.487,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,4315.0000,0.0,0.0
8107,8107,F37523,5926.0,E,2.0,2022-02-28 17:36:54.363,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,451.6100,0.0,0.0
8133,8133,F37549,3016.0,E,1.0,2022-03-04 15:08:49.747,2022-03-04,2022-02-28 00:00:00,2022-03-04,NaN,1083.7200,0.0,0.0
8148,8148,F37564,4695.0,E,1.0,2022-03-08 09:15:20.507,2022-03-08,2022-02-28 00:00:00,2022-05-07,NaN,5515.0000,0.0,0.0
8204,8204,F37620,8316.0,E,3.0,2022-03-14 17:00:43.247,2022-03-14,2022-02-28 00:00:00,2022-03-14,NaN,24570.3000,0.0,0.0

In [21]:
df3.to_csv("df3.csv")

In [ ]:
##ejercicio 4 CAN_TOT < 5951.7  OR  STATUS == "E"
df4 = df[(df["CAN_TOT"] < 5951.7) | (df["STATUS"] == "E")]
df4

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,0,F29414,2465.0,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0.0
1,1,F29415,3926.0,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
2,2,F29416,3926.0,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
3,3,F29417,3926.0,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0.0
4,4,F29418,6813.0,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10890,10890,F40306,8842.0,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaN,3272.00,0.0,0.0
10891,10891,F40307,6218.0,NaN,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaN,504.15,0.0,0.0
10892,10892,NaN,5926.0,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaN,275.68,0.0,0.0
10893,10893,F40309,361.0,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaN,129.30,0.0,0.0
10894,10894,F40310,3011.0,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaN,517.20,0.0,0.0

In [22]:
df4.to_csv("df4.csv")

In [ ]:
##ejercicio 5 solo columnas: CVE_DOC, FECHA_ENT, FECHA_VEN, CAN_TOT
df5 = df[["CVE_DOC", "FECHA_ENT", "FECHA_VEN", "CAN_TOT"]]
df5

      CVE_DOC            FECHA_ENT   FECHA_VEN  CAN_TOT
0      F29414  2019-09-03 00:00:00  2019-09-18  3980.00
1      F29415  2019-09-03 00:00:00  2019-10-03  1550.00
2      F29416  2019-09-03 00:00:00  2019-10-03  1550.00
3      F29417  2019-09-03 00:00:00  2019-10-03  1550.00
4      F29418  2019-09-03 00:00:00  2019-09-03  2435.44
...       ...                  ...         ...      ...
10890  F40306  2023-03-01 00:00:00  2023-03-06  3272.00
10891  F40307  2023-03-06 00:00:00  2023-03-06   504.15
10892     NaN  2023-03-06 00:00:00  2023-03-06   275.68
10893  F40309  2023-03-07 00:00:00  2023-03-07   129.30
10894  F40310  2023-03-01 00:00:00  2023-03-07   517.20

[10817 rows x 4 columns]

In [23]:
df5.to_csv("df5.csv")

In [ ]:
##Ejercicio 6 solo filas 7001‚Äì7099 
df6 = df.iloc[7000:7100]
df6

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
7053,7053,F36469,401.0,E,2.0,2021-10-21 12:07:23.947,2021-10-21,2021-10-20 00:00:00,2021-11-05,NaN,1392.0000,0.0,0.0
7054,7054,F36470,3803.0,E,2.0,2021-10-21 12:51:34.323,2021-10-21,2021-10-20 00:00:00,2021-11-20,NaN,5450.0000,0.0,0.0
7055,7055,F36471,8145.0,E,1.0,2021-10-21 13:01:19.650,2021-10-21,2021-10-18 00:00:00,2021-10-21,NaN,24300.0000,0.0,0.0
7056,7056,F36472,8316.0,E,2.0,2021-10-21 13:04:29.287,2021-10-21,2021-10-21 00:00:00,2021-10-21,NaN,9500.0000,0.0,0.0
7057,7057,F36473,5598.0,E,2.0,2021-10-21 13:09:55.180,2021-10-21,2021-10-20 00:00:00,2021-10-21,NaN,1988.8000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7148,7148,F36564,4714.0,E,3.0,2021-11-03 10:14:02.213,2021-11-03,2021-11-02 00:00:00,2021-11-03,NaN,3875.2908,0.0,0.0
7149,7149,F36565,3033.0,E,1.0,2021-11-03 10:16:23.907,2021-11-03,2021-11-02 00:00:00,2021-11-03,NaN,851.7993,0.0,0.0
7150,7150,F36566,8229.0,E,2.0,2021-11-03 10:20:01.277,2021-11-03,2021-11-03 00:00:00,2021-11-03,NaN,753.0000,0.0,0.0
7151,7151,F36567,8495.0,E,3.0,2021-11-03 10:29:57.950,2021-11-03,2021-11-02 00:00:00,2021-11-03,NaN,1647.3000,0.0,0.0
7152,7152,F36568,8496.0,C,1.0,2021-11-03 10:31:23.073,2021-11-03,2021-11-02 00:00:00,2021-11-03,2021-11-03,425.0000,0.0,0.0

In [24]:
df6.to_csv("df6.csv")

In [ ]:
##Ejercicio 7 index = CVE_VEND(valores 1,2) (columna: FECHALAB)
df7 = df[df["CVE_VEND"].isin([1, 2])].set_index("FECHAELAB")
df7

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
FECHAELAB,,,,,,,,,,,,
2019-09-03 08:58:42.000,0,F29414,2465.0,C,1.0,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0.0
2019-09-03 09:55:14.000,1,F29415,3926.0,C,1.0,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
2019-09-03 13:25:33.000,2,F29416,3926.0,C,1.0,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
2019-09-03 13:33:23.000,3,F29417,3926.0,C,1.0,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0.0
2019-09-03 14:23:45.000,4,F29418,6813.0,C,2.0,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2023-03-06 16:09:39.013,10890,F40306,8842.0,E,2.0,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaN,3272.00,0.0,0.0
2023-03-06 16:38:42.933,10891,F40307,6218.0,NaN,2.0,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaN,504.15,0.0,0.0
2023-03-06 17:02:33.390,10892,NaN,5926.0,E,2.0,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaN,275.68,0.0,0.0
2023-03-07 12:43:49.567,10893,F40309,361.0,E,2.0,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaN,129.30,0.0,0.0
2023-03-07 12:45:58.407,10894,F40310,3011.0,E,2.0,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaN,517.20,0.0,0.0

In [25]:
df7.to_csv("df7.csv")